# Generated by Django 5.1.2 on 2024-10-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cutter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoria', models.CharField(max_length=255)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
