# Generated by Django 5.1.2 on 2024-10-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutter',
            name='autoria',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cutter',
            name='titulo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
