# Generated by Django 5.1.2 on 2024-10-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0002_alter_cutter_autoria_alter_cutter_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cutter',
            options={'ordering': ['autoria']},
        ),
    ]
