# Generated by Django 5.1.2 on 2024-10-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0003_alter_cutter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutter',
            name='autoria',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cutter',
            name='titulo',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
