# Generated by Django 5.1.2 on 2024-10-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0004_alter_cutter_autoria_alter_cutter_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutter',
            name='autoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cutter',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
